# nixos/hardware-configurations/k3s-master.nix
# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  # Root filesystem configuration specific to this machine
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/77f6fe61-3fa3-4728-9fb9-7c37c5a40f4a";
      fsType = "ext4";
    };

  # Enable SSD TRIM
  services.fstrim.enable = true;
}
