# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  # Root filesystem configuration specific to this machine
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/798375fd-547b-4c0e-8d26-a3c50c1ed957";
      fsType = "ext4";
    };

  # Enable SSD TRIM
  services.fstrim.enable = true;
}
