apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token
  namespace: cloudflare-tunnel
type: Opaque
data:
  token: ZXlKaElqb2lZemxsTnpFM01tTmpaREpqTnpObU56bGpPR00wWkRNM1lUZGhZbUZoTVRVaUxDSjBJam9pTUdSbE9UUm1aR1V0WWpCak1DMDBNbVkwTFdJNFl6QXRZemczTUdRM016QTBaRFl3SWl3aWN5STZJbHBVV1hoYVIwMTRUMFJKZEUxcVp6SmFRekF3VFZSbk1VeFhSbTFPYWtsMFdYcHNhMXBIVFhwTlJFbDRUbnBSTlNKOQ==
