apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"jellyfin","namespace":"jellyfin"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jellyfin"}},"template":{"metadata":{"labels":{"app":"jellyfin"}},"spec":{"containers":[{"image":"jellyfin/jellyfin:latest","name":"jellyfin","ports":[{"containerPort":8096,"name":"http"}],"resources":{"limits":{"cpu":"8","memory":"8Gi"},"requests":{"cpu":"4","memory":"4Gi"}},"volumeMounts":[{"mountPath":"/media","name":"media","readOnly":true},{"mountPath":"/config","name":"config"}]}],"volumes":[{"name":"media","persistentVolumeClaim":{"claimName":"media-nfs-pvc"}},{"name":"config","persistentVolumeClaim":{"claimName":"jellyfin-config-pvc"}}]}}}}
  creationTimestamp: "2025-09-08T03:37:35Z"
  generation: 4
  name: jellyfin
  namespace: jellyfin
  resourceVersion: "277012"
  uid: e091a090-fff6-4699-a8f6-aa919f5f5011
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jellyfin
    spec:
      containers:
        - image: jellyfin/jellyfin:latest
          imagePullPolicy: Always
          name: jellyfin
          ports:
            - containerPort: 8096
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "8"
              memory: 8Gi
            requests:
              cpu: "4"
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /media
              name: media
              readOnly: true
            - mountPath: /config
              name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-nfs-pvc
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2025-09-08T14:22:18Z"
      lastUpdateTime: "2025-09-08T14:22:18Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-09-08T04:02:37Z"
      lastUpdateTime: "2025-09-08T16:59:44Z"
      message: ReplicaSet "jellyfin-7b889cd948" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
