# manifests/database/pgadmin-server-config.yaml
# Additional server configurations for pgAdmin
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers-config
  namespace: database
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Homelab PostgreSQL - All Databases",
          "Group": "Homelab",
          "Host": "shared-postgresql.database.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "prefer",
          "Comment": "Main PostgreSQL server with all service databases"
        },
        "2": {
          "Name": "Nextcloud Database",
          "Group": "Applications",
          "Host": "shared-postgresql.database.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "nextcloud",
          "Username": "nextcloud",
          "SSLMode": "prefer",
          "Comment": "Nextcloud application database"
        },
        "3": {
          "Name": "Gitea Database",
          "Group": "Applications",
          "Host": "shared-postgresql.database.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "gitea",
          "Username": "gitea",
          "SSLMode": "prefer",
          "Comment": "Gitea Git hosting database"
        },
        "4": {
          "Name": "Immich Database",
          "Group": "Applications",
          "Host": "shared-postgresql.database.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "immich",
          "Username": "immich",
          "SSLMode": "prefer",
          "Comment": "Immich photo management database with vector extensions"
        },
        "5": {
          "Name": "Kasm Database",
          "Group": "Applications",
          "Host": "shared-postgresql.database.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "kasm",
          "Username": "kasm",
          "SSLMode": "prefer",
          "Comment": "Kasm Workspaces virtual desktop database"
        },
        "6": {
          "Name": "Vaultwarden Database",
          "Group": "Applications",
          "Host": "shared-postgresql.database.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "vaultwarden",
          "Username": "vaultwarden",
          "SSLMode": "prefer",
          "Comment": "Vaultwarden password manager database"
        },
        "7": {
          "Name": "Jenkins Database",
          "Group": "Applications",
          "Host": "shared-postgresql.database.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "jenkins",
          "Username": "jenkins",
          "SSLMode": "prefer",
          "Comment": "Jenkins CI/CD database for plugins and configuration"
        }
      }
    }
