# manifests/database/pgadmin-secrets.yaml
# Password secrets for pgAdmin server connections
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-db-passwords
  namespace: database
type: Opaque
stringData:
  # These should match the passwords from your shared-postgresql setup
  postgres_password: "homelab_admin_password"
  nextcloud_password: "nextcloud_password"
  gitea_password: "gitea_password"
  immich_password: "immich_password"
  kasm_password: "kasm_password"
  vaultwarden_password: "vaultwarden_password"
  jenkins_password: "jenkins_password"
