# manifests/database/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
type: Opaque
stringData:
  postgresql-host: "postgresql.database.svc.cluster.local"
  postgresql-port: "5432"
  postgresql-database: "nextcloud"
  postgresql-username: "nextcloud"
  postgresql-password: "nextcloud_password"

---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-db-secret
  namespace: developer
type: Opaque
stringData:
  postgresql-host: "postgresql.database.svc.cluster.local"
  postgresql-port: "5432"
  postgresql-database: "gitea"
  postgresql-username: "gitea"
  postgresql-password: "gitea_password"

---
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
  namespace: immich
type: Opaque
stringData:
  postgresql-host: "postgresql.database.svc.cluster.local"
  postgresql-port: "5432"
  postgresql-database: "immich"
  postgresql-username: "immich"
  postgresql-password: "immich_password"

---
apiVersion: v1
kind: Secret
metadata:
  name: kasm-db-secret
  namespace: kasm
type: Opaque
stringData:
  postgresql-host: "postgresql.database.svc.cluster.local"
  postgresql-port: "5432"
  postgresql-database: "kasm"
  postgresql-username: "kasm"
  postgresql-password: "kasm_password"

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-db-secret
  namespace: developer
type: Opaque
stringData:
  postgresql-host: "postgresql.database.svc.cluster.local"
  postgresql-port: "5432"
  postgresql-database: "jenkins"
  postgresql-username: "jenkins"
  postgresql-password: "jenkins_password"

---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-db-secret
  namespace: vaultwarden
type: Opaque
stringData:
  postgresql-host: "postgresql.database.svc.cluster.local"
  postgresql-port: "5432"
  postgresql-database: "vaultwarden"
  postgresql-username: "vaultwarden"
  postgresql-password: "vaultwarden_password"
