# applications/authentik-config.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20" # Run after the main authentik app
spec:
  project: default
  source:
    repoURL: https://github.com/jake-molnia/homelab
    targetRevision: HEAD
    path: manifests/authentik
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
