# applications/authentik.yaml - Fixed Authentik Helm chart
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2025.8.3
    helm:
      values: |
        authentik:
          # Secret key for signing cookies
          secret_key: "PleaseGenerateASecureKey-ChangeThis60CharString12345678"
          log_level: info
          error_reporting:
            enabled: false

        # Global configuration for external database
        global:
          env:
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: "shared-postgresql.database.svc.cluster.local"
            - name: AUTHENTIK_POSTGRESQL__PORT
              value: "5432"
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: "authentik"
            - name: AUTHENTIK_POSTGRESQL__USER
              value: "authentik"
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-passwords
                  key: authentik-password

        # Disable built-in PostgreSQL
        postgresql:
          enabled: false

        # Redis configuration
        redis:
          enabled: true
          auth:
            enabled: false
          master:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 5Gi

        # Server configuration
        server:
          ingress:
            enabled: false  # Will be handled by authentik-config app
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"

        # Worker configuration
        worker:
          enabled: true
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"

        # Disable GeoIP
        geoip:
          enabled: false

        # Service Account
        serviceAccount:
          create: true

        # Persistent volumes for media and templates
        persistence:
          media:
            enabled: true
            storageClass: longhorn
            size: 10Gi
          templates:
            enabled: true
            storageClass: longhorn
            size: 1Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
