# applications/immich.yaml - Updated to use shared DB
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/immich-app/immich-charts
    chart: immich
    targetRevision: 0.9.3
    helm:
      values: |
        env:
          TZ: "America/New_York"
          DB_HOSTNAME: shared-postgresql-postgresql.database.svc.cluster.local
          DB_PORT: "5432"
          DB_USERNAME: immich
          DB_PASSWORD: "immich_password"
          DB_DATABASE_NAME: immich

        image:
          tag: v1.119.0

        immich:
          persistence:
            library:
              existingClaim: immich-library-pvc

        server:
          enabled: true
          ingress:
            main:
              enabled: true
              ingressClassName: tailscale
              hosts:
                - host: immich
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - hosts:
                    - immich

        machine-learning:
          enabled: true
          persistence:
            cache:
              enabled: true
              storageClass: longhorn
              size: 10Gi

        # DISABLE built-in PostgreSQL
        postgresql:
          enabled: false

        redis:
          enabled: true
          architecture: standalone
          auth:
            enabled: false
          master:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
