apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator
    targetRevision: HEAD
    path: deploy/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-operator-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator
    targetRevision: HEAD
    path: deploy/all-in-one-v1alpha2
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
