# applications/kasm.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasm-workspaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://helm.kasmweb.com/
    chart: kasm-single-zone
    helm:
      values: |
        global:
          hostname: kasm

        namespace: kasm

        # Use centralized PostgreSQL
        postgres:
          host: "shared-postgresql.database.svc.cluster.local"
          port: 5432
          sslMode: "prefer"
          database: "kasm"
          username: "kasm"
          # Password will be set via secret

        # Kasm component configurations
        api:
          replicaCount: 2
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"

        manager:
          replicaCount: 1
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"

        share:
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"

        guac:
          replicaCount: 2
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"

        # Ingress configuration for Tailscale
        ingress:
          enabled: true
          className: tailscale
          hosts:
            - host: kasm
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - kasm

        # Storage for uploads
        persistentVolumeClaim:
          uploads:
            storageClassName: longhorn
            size: 50Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: kasm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
