apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.9.1
    helm:
      values: |
        defaultSettings:
          defaultDataPath: /data/longhorn
          createDefaultDiskLabeledNodes: true
          defaultReplicaCount: 2
          storageOverProvisioningPercentage: 100
          storageMinimalAvailablePercentage: 25
          upgradeChecker: false

        # CRITICAL: This fixes ArgoCD installation issues
        preUpgradeChecker:
          jobEnabled: false

        longhornManager:
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

        longhornDriver:
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

        longhornUI:
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

        csi:
          kubeletRootDir: /var/lib/kubelet
          attacherReplicaCount: 1
          provisionerReplicaCount: 1
          resizerReplicaCount: 1
          snapshotterReplicaCount: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
