# applications/nextcloud.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 5.5.2
    helm:
      values: |
        image:
          tag: 30-apache

        nextcloud:
          host: nextcloud
          username: admin
          password: "changeme123"

        persistence:
          enabled: true
          storageClass: longhorn
          size: 100Gi
          nextcloudData:
            enabled: true
            storageClass: longhorn
            size: 500Gi

        postgresql:
          enabled: true
          global:
            postgresql:
              auth:
                username: nextcloud
                database: nextcloud
                password: nextcloud
          primary:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 20Gi

        redis:
          enabled: true
          auth:
            enabled: false
          master:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 5Gi

        ingress:
          enabled: true
          className: tailscale
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          tls:
            - hosts:
                - nextcloud

        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
