# applications/pgadmin.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10" # Deploy after database but before apps
spec:
  project: default
  source:
    repoURL: https://helm.runix.net
    chart: pgadmin4
    targetRevision: 1.50.0
    helm:
      values: |
        # pgAdmin Configuration
        env:
          email: admin@homelab.local
          password: "pgadmin_admin_password"  # Change this!

        # Enable persistence for pgAdmin settings
        persistentVolume:
          enabled: true
          storageClass: longhorn
          size: 10Gi

        # Security context
        securityContext:
          runAsUser: 5050
          runAsGroup: 5050
          fsGroup: 5050

        # Resources
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "256Mi"

        # Service configuration
        service:
          type: ClusterIP
          port: 80

        # Ingress for Tailscale
        ingress:
          enabled: true
          className: tailscale
          hosts:
            - host: pgadmin
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - pgadmin

        # Pre-configure server connections
        serverDefinitions:
          enabled: true
          servers:
            homelab-postgres:
              Name: "Homelab PostgreSQL"
              Group: "Homelab"
              Host: "shared-postgresql.database.svc.cluster.local"
              Port: 5432
              Username: "postgres"
              SSLMode: "prefer"
              MaintenanceDB: "postgres"

        # Network policy for security
        networkPolicy:
          enabled: true

        # Probes for health checking
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10

        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5

  destination:
    server: https://kubernetes.default.svc
    namespace: database # Deploy in database namespace with PostgreSQL
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false # Database namespace already exists
