# applications/postgresql.yaml - Clean shared PostgreSQL
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 13.2.24
    helm:
      values: |
        global:
          postgresql:
            auth:
              postgresPassword: "homelab_admin_password"
              database: "homelab"
              username: "homelab"
              password: "homelab_user_password"

        primary:
          persistence:
            enabled: true
            storageClass: longhorn
            size: 200Gi

          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "1"
              memory: "2Gi"

          configuration: |
            max_connections = 200
            shared_buffers = 2GB
            effective_cache_size = 6GB
            wal_buffers = 16MB
            checkpoint_completion_target = 0.9
            random_page_cost = 1.1
            effective_io_concurrency = 200
            listen_addresses = '*'
            pg_hba.conf = |
              host all all 0.0.0.0/0 md5

        service:
          type: ClusterIP
          ports:
            postgresql: 5432

  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
