# applications/postgresql.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5" # Deploy before everything else
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 16.7.27
    helm:
      values: |
        auth:
          postgresPassword: "homelab_admin_password"
          database: "homelab"
          username: "homelab"
          password: "homelab_user_password"

        primary:
          persistence:
            enabled: true
            storageClass: longhorn
            size: 100Gi

          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "1Gi"

          # Create multiple databases for different services
          initdb:
            scripts:
              01-create-databases.sql: |
                -- Create databases for different services
                CREATE DATABASE nextcloud;
                CREATE DATABASE gitea;
                CREATE DATABASE immich;
                CREATE DATABASE kasm;
                CREATE DATABASE vaultwarden;
                CREATE DATABASE jenkins;

                -- Create users for different services
                CREATE USER nextcloud WITH PASSWORD 'nextcloud_password';
                CREATE USER gitea WITH PASSWORD 'gitea_password';
                CREATE USER immich WITH PASSWORD 'immich_password';
                CREATE USER kasm WITH PASSWORD 'kasm_password';
                CREATE USER vaultwarden WITH PASSWORD 'vaultwarden_password';
                CREATE USER jenkins WITH PASSWORD 'jenkins_password';

                -- Grant privileges
                GRANT ALL PRIVILEGES ON DATABASE nextcloud TO nextcloud;
                GRANT ALL PRIVILEGES ON DATABASE gitea TO gitea;
                GRANT ALL PRIVILEGES ON DATABASE immich TO immich;
                GRANT ALL PRIVILEGES ON DATABASE kasm TO kasm;
                GRANT ALL PRIVILEGES ON DATABASE vaultwarden TO vaultwarden;
                GRANT ALL PRIVILEGES ON DATABASE jenkins TO jenkins;

                -- For Immich vector extension
                \c immich;
                CREATE EXTENSION IF NOT EXISTS cube;
                CREATE EXTENSION IF NOT EXISTS earthdistance;
                CREATE EXTENSION IF NOT EXISTS vectors;

        # Enable backup
        backup:
          enabled: true
          cronjob:
            schedule: "0 2 * * *"  # Daily at 2 AM
            storage:
              storageClass: longhorn
              size: 50Gi

        # Enable metrics
        metrics:
          enabled: true
          serviceMonitor:
            enabled: false  # Enable if you have Prometheus operator

        service:
          type: ClusterIP
          ports:
            postgresql: 5432

  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
