# applications/vaultwarden.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  source:
    repoURL: https://charts.gabe565.com
    chart: vaultwarden
    targetRevision: 0.6.1
    helm:
      values: |
        env:
          TZ: "America/New_York"
          WEBSOCKET_ENABLED: "true"
          DOMAIN: "https://vaultwarden"
          DISABLE_ADMIN_TOKEN: "true"

        persistence:
          data:
            enabled: true
            storageClass: longhorn
            size: 10Gi

        ingress:
          main:
            enabled: true
            ingressClassName: tailscale
            hosts:
              - host: vaultwarden
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - vaultwarden

        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
