apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-ldap-service
  namespace: authentik
data:
  service.yaml: |
    # Service to expose LDAP outpost internally
    apiVersion: v1
    kind: Service
    metadata:
      name: authentik-ldap-outpost
      namespace: authentik
    spec:
      selector:
        app.kubernetes.io/name: authentik-ldap-outpost
      ports:
        - name: ldap
          port: 389
          targetPort: 3389
        - name: ldaps
          port: 636
          targetPort: 6636
      type: ClusterIP
