apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
type: Opaque
stringData:
  client_id: "khgjVHqCy511CNTRL"
  client_secret: "tskey-client-khgjVHqCy511CNTRL-EKg8wR1XUxATq8RzAhWpxAPL7qeCyU8pH"