---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-shared-nfs-pv
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - tcp
    - noatime
    - nodiratime
  nfs:
    server: 10.10.10.11
    path: /mnt/data/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-shared-nfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  volumeName: media-shared-nfs-pv
