apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.10.11
    path: /mnt/data/media
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" # Empty string for manual binding
  resources:
    requests:
      storage: 2Ti
  volumeName: jellyfin-media-pv
