apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  version: 1.7.1
  targetNamespace: longhorn-system
  valuesContent: |-
    # Use /data directory for storage
    defaultSettings:
      defaultDataPath: /data/longhorn
      createDefaultDiskLabeledNodes: true

    # Backup configuration - you can modify these
      backupTarget: "" # Set to s3://bucket-name or nfs://server/path
      backupTargetCredentialSecret: "" # Secret name for backup credentials

    # Performance optimizations
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 25
      upgradeChecker: false
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod

    # Replica settings
      defaultReplicaCount: 2
      defaultLonghornStaticStorageClass: longhorn

    # Resource settings
    longhornManager:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi

    longhornDriver:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi

    longhornUI:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi

    # Enable metrics for monitoring
    longhornManager:
      serviceMonitor:
        enabled: false # Set to true if you have Prometheus operator

    # CSI settings
    csi:
      kubeletRootDir: /var/lib/kubelet
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1

    # Image settings
    image:
      longhorn:
        engine:
          repository: longhornio/longhorn-engine
          tag: v1.7.1
        manager:
          repository: longhornio/longhorn-manager
          tag: v1.7.1
        ui:
          repository: longhornio/longhorn-ui
          tag: v1.7.1
        instanceManager:
          repository: longhornio/longhorn-instance-manager
          tag: v1.7.1
        shareManager:
          repository: longhornio/longhorn-share-manager
          tag: v1.7.1
        backingImageManager:
          repository: longhornio/backing-image-manager
          tag: v1.7.1
        supportBundleKit:
          repository: longhornio/support-bundle-kit
          tag: v0.0.42

    # Service settings
    service:
      ui:
        type: ClusterIP
        nodePort: null
      manager:
        type: ClusterIP
        nodePort: null
