---
# Longhorn Settings - Modify these as needed
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-data-path: "/data/longhorn"
  replica-soft-anti-affinity: "false"
  replica-auto-balance: "disabled"
  storage-over-provisioning-percentage: "100"
  storage-minimal-available-percentage: "25"
  upgrade-checker: "false"
  default-replica-count: "2"
  default-longhorn-static-storage-class: "longhorn"
  node-down-pod-deletion-policy: "delete-both-statefulset-and-deployment-pod"

  # Backup settings - uncomment and modify as needed
  # backup-target: "s3://your-backup-bucket@region/"
  # backup-target-credential-secret: "longhorn-backup-secret"

  # NFS backup example:
  # backup-target: "nfs://10.10.10.11:/mnt/data/backups/longhorn"

  # Performance settings
  concurrent-automatic-engine-upgrade-per-node-limit: "1"
  default-data-locality: "disabled"
  replica-zone-soft-anti-affinity: "true"

  # Snapshot settings
  snapshot-data-integrity: "ignored"
  snapshot-data-integrity-immediate-check-after-snapshotting: "false"
  snapshot-data-integrity-cronjob: "ignored"

---
# Secret for backup credentials (example for S3)
# Uncomment and modify if using S3 backup
# apiVersion: v1
# kind: Secret
# metadata:
#   name: longhorn-backup-secret
#   namespace: longhorn-system
# type: Opaque
# data:
#   AWS_ACCESS_KEY_ID: # base64 encoded access key
#   AWS_SECRET_ACCESS_KEY: # base64 encoded secret key
#   AWS_ENDPOINTS: # base64 encoded endpoint URL (optional)

# ---
# # Example recurring backup job
# apiVersion: longhorn.io/v1beta2
# kind: RecurringJob
# metadata:
#   name: daily-backup
#   namespace: longhorn-system
# spec:
#   cron: "0 2 * * *"  # Daily at 2 AM
#   task: "backup"
#   groups:
#     - default
#   retain: 7  # Keep 7 backups
#   concurrency: 2
#   labels:
#     recurring-job-group: backup
