apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: homelab
  labels:
    app: nginx-test
    managed-by: nixos
spec:
  selector:
    app: nginx-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
