# manifests/kasm/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kasm-uploads
  namespace: kasm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
