---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-pvc
  namespace: personal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: personal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-data-pvc
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: WEBSOCKET_ENABLED
              value: "true"
            - name: ROCKET_PORT
              value: "80"
            - name: DATA_FOLDER
              value: "/data"
            - name: TZ
              value: "America/New_York"
            # Disable admin panel for security (enable only when needed)
            - name: DISABLE_ADMIN_TOKEN
              value: "true"
            # Enable HTTPS (since we're using Traefik TLS)
            - name: DOMAIN
              value: "https://vaultwarden.homelab.local"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: personal
spec:
  selector:
    app: vaultwarden
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  namespace: personal
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - vaultwarden
  rules:
    - host: vaultwarden
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  number: 80