apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-nfs-pvc
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc # Your existing config - preserved!
        # NEW: NVMe cache for transcoding
        - name: cache
          persistentVolumeClaim:
            claimName: jellyfin-cache-pvc
        # NEW: Memory cache for small temp files
        - name: tmp-cache
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          ports:
            - containerPort: 8096
              name: http
          # NEW: Performance environment variables
          env:
            - name: JELLYFIN_PublishedServerUrl
              value: "https://jellyfin.homelab.local"
            # FFmpeg optimizations for better transcoding
            - name: JELLYFIN_FFmpeg__threads
              value: "12" # Use more CPU threads
            - name: JELLYFIN_FFmpeg__probesize
              value: "50000000" # 50MB probe for large files
            - name: JELLYFIN_FFmpeg__analyzeduration
              value: "50000000" # 50MB analyze duration
            # .NET runtime optimizations
            - name: DOTNET_GCConserveMemory
              value: "3" # Balanced garbage collection
            - name: DOTNET_GCHeapHardLimit
              value: "10000000000" # 10GB GC limit
            # Reduce logging for performance
            - name: JELLYFIN_FFMPEG_VERBOSITY
              value: "error"
          volumeMounts:
            - name: media
              mountPath: /media
              readOnly: true
            - name: config
              mountPath: /config # Your existing config unchanged
            # NEW: Fast transcoding cache on NVMe
            - name: cache
              mountPath: /config/transcodes
            # NEW: Fast temp directory in memory
            - name: tmp-cache
              mountPath: /tmp
          # INCREASED: More resources for better performance
          resources:
            limits:
              cpu: "16" # Increased from 8 to 16 cores
              memory: "12Gi" # Increased from 8 to 12GB
            requests:
              cpu: "6" # Increased from 4 to 6 cores
              memory: "6Gi" # Increased from 4 to 6GB
          # IMPROVED: Better health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 90 # More time for startup
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 2
          # NEW: Graceful shutdown for transcoding
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
